# Параметры MQTT-соединения
MQTT_PARAMS = {'PUBLISHER': "lutyisan", # Имя клиента (любое)
               'TRANSPORT': "websockets", # Выбор протокола tcp или websockets
               'PATH': "/ws", # URL
               'USER_NAME': "user", # Логин
               'USER_PASS': "user",  # Пароль
               'HOST': "mq.4iot.pro",  # Адрес брокера
               'PORT': 15675,  # Порт брокера
               'SLEEPING_TIME': 3} # Период оиправки данных

# dict девайса с сигналами
heat_counter = {'name': "heatCounter",
             'TE-1': 56,
             "TE-2": 34,
             'TE-3': 70,
             "TE-4": 60,
             "PE-1": 3.5,
             "PE-2": 2.8,
             "PE-3": 4.2,
             "PE-4": 3.5,
             "massa-in": 2321,
             "massa-out": 923,
             "volume-in": 628,
             "volume-out": 23,
             "heat-power": 2456,
             "heat-energy": 786}

# dict девайса с сигналами
el_counter = {'name': "esCounter",
           'volt-a': 221,
           "volt-b": 219,
           'volt-c': 223,
           "curr-a": 34,
           "curr-b": 32,
           "curr-c": 29,
           "act-en": 2245,
           "react-en": 237,
           "full-en": 2700,
           "act-pow": 6.00,
           "react-pow": 4.00,
           "full-pow": 9.00,
           }

# dict девайса с сигналами
cool_water_counter = {"name": 'coolWater', "volume": 4356}

# dict девайса с сигналами
heat_water_counter = {'name': "heatWater", "volume": 3871}

# dict девайса с сигналами
dn_station = {'name': "dnStation",
                   "pump1-work": False,
                   "pump1-alarm": True,
                   "pump2-work": False,
                   "pump2-alarm": True,
                   "ls-1": True,
                   "ls-2": False,
                   "ls-3": False}

# dict девайса с сигналами
ahu = {'name': "ahu",
                   "te-oat": 25.8,
                   "te-sf": 23.1,
                   "te-rf": 24.5,
                   "te-heat": 38.3,
                   "heat-valve": 10.0,
                   "cool-valve": 76.2,
                   "rec-valve": 10.6,
                   "sf-state": True,
                   "rf-state": False,
                   "heat-pump-state": False,
                   "cool-pump-state": True,
                   "rec-pump-state": False,
                   "sf-dumper": True,
                   "rf-dumper": False,
                   "rec-dumper": True,
                   "termostat": False,
                   "flter-1": True,
                   "filter-2": True,
                   "filter-3": False,
                   "start-ahu": True,
                   "temp-set": 22,
                   "season": 1,
                   "start-heat-pump": 2,
                   "start-cool-pump": 2,
                   "start-rec-pump": 2,
                   "start-sf-dumper": True,
                   "start-rf-dumper": False,
                   "start-rec-dumper": True
                   }
itp = {"name": "itp",
       "te-1": 68.3,
       "te-2": 62.3,
       "te-3": 60.3,
       "te-4": 51.3,
       "te-5": 65.3,
       "te-6": 57.3,
       "pe-1": 4.6,
       "pe-2": 3.6,
       "pe-3": 4.4,
       "pe-4": 4.1,
       "valve-1": 34,
       "valve-2": 12,
       "pump-1": True,
       "pump-2": False,
       "pump-3": False,
       "pump-4": True,
       "dps-1": True,
       "dps-2": False,
       "dps-3": False,
       "dps-4": True,
       "set-gvs-temp": 55.0,
       "set-ot-temp": 68
       }
grp = {"name": "grp",
       "qs-on": True,
       "qs-off": True,
       "qs-alarm": True,
       "1qs-on": True,
       "1qs-off": True,
       "1qs-alarm": True,
       "2qs-on": True,
       "2qs-off": True,
       "2qs-alarm": True,
       "1qf1-on": True,
       "1qf1-off": False,
       "1qf1-alarm": False,
       "1qf2-on": True,
       "1qf2-off": False,
       "1qf2-alarm": False,
       "1qf3-on": True,
       "1qf3-off": False,
       "1qf3-alarm": False,
       "1qf4-on": True,
       "1qf4-off": False,
       "1qf4-alarm": False,
       "1qf5-on": True,
       "1qf5-off": False,
       "1qf5-alarm": False,
       "2qf1-on": True,
       "2qf1-off": False,
       "2qf1-alarm": False,
       "2qf2-on": True,
       "2qf2-off": False,
       "2qf2-alarm": False,
       "2qf3-on": True,
       "2qf3-off": False,
       "2qf3-alarm": False,
       "2qf4-on": True,
       "2qf4-off": False,
       "2qf4-alarm": False,
       "2qf5-on": True,
       "2qf5-off": False,
       "2qf5-alarm": False,
       "2qf6-on": True,
       "2qf6-off": False,
       "2qf6-alarm": False
       }
light = {"name": "light",
         "lamp-1": True,
         "lamp-1-start": True,
         "lamp-1-dimm": 50,
         "lamp-2": True,
         "lamp-2-start": True,
         "lamp-2-dimm": 50,
         "lamp-3": True,
         "lamp-3-start": True,
         "lamp-3-dimm": 50,
         "lamp-4": True,
         "lamp-4-start": True,
         "lamp-4-dimm": 50,
         "lamp-5": True,
         "lamp-5-start": True,
         "lamp-5-dimm": 50,
         "lamp-6": True,
         "lamp-6-start": True,
         "lamp-6-dimm": 50,
         "lamp-7": True,
         "lamp-7-start": True,
         "lamp-7-dimm": 50,
         "lamp-8": True,
         "lamp-8-start": True,
         "lamp-8-dimm": 50,
         "lamp-9": True,
         "lamp-9-start": True,
         "lamp-9-dimm": 50,
         "lamp-10": True,
         "lamp-10-start": True,
         "lamp-10-dimm": 50,
         "lamp-11": True,
         "lamp-11-start": True,
         "lamp-11-dimm": 50,
         "lamp-12": True,
         "lamp-12-start": True,
         "lamp-12-dimm": 50
         }
water_station = {"name": "waterStation",
                 "pe-1": 1.4,
                 "pe-2": 3.2,
                 "pe-3": 3.1,
                 "pe-4": 3.4,
                 "pe-5": 3.4,
                 "pump-1": True,
                 "pump-2": True,
                 "pump-3": True,
                 "pump-1-start": True,
                 "pump-2-start": True,
                 "pump-3-start": True,
                 "start": True
                 }

cool_center = {"name": "coolCenter", "te-1": 13.4, "pe-1": 6.2, "te-2": 11.1, "pe-2": 2.7, "te-3": 10.3, "pe-3": 2.9,"pe-4": 6.9,"pe-9": 2.9,
               "pe-5": 4.4, "pe-10": 5.3, "pe-6": 4.5,"pe-7": 2.9, "te-4": 11.2,"pe-8": 6.0,"pe-11": 0.1, "pe-12": 0.1,
               "pe-13": 0.1, "pe-14": 11.1,"te-5": 8.9, "y1": False, "y5": True,"y2": True, "y3": False,"y4": False,
               "y6": False, "y7": False, "y8": True, "y9": True,"uao1": False, 'uao2': True, "uoo": False,"dps1": True,
               "dps2": False,"nc1": True, "nc2": False, "nc3": True, "nc4": False}

lift = {"name": "lift", "stage-1": False,"stage-2": False,"stage-3": False,"stage-4": False,"stage-5": False,"stage-6": False,"stage-7": False, "door": False }

DEVICES = [heat_counter, el_counter, cool_water_counter, heat_water_counter, dn_station,ahu, itp, grp, light, water_station, cool_center, lift]